# Build
FROM node:22-alpine AS builder
WORKDIR /opt

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# Producción
FROM nginx:alpine AS production
COPY --from=builder /opt/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

# Desarrollo
FROM node:22-alpine AS development
WORKDIR /opt

COPY package*.json ./
RUN npm ci

COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]